### PR TITLE
LIB-641 feat(dialog): escape key listener

### PR DESCRIPTION
**Pull request by Trebh**
[Jira](https://fiscozen.atlassian.net/browse/LIB-641)

### CODE REVIEW

**Comment by Trebh** [comment]
I also changed the name of the event, I don't see counterpoints

**Review by oxcened — COMMENTED** [review]
you should reuse this one
https://github.com/fiscozen/design_system/blob/main/packages/composables/src/composables/useKeyDown.ts

**Comment by Trebh** [comment]
> you should reuse this one https://github.com/fiscozen/design_system/blob/main/packages/composables/src/composables/useKeyDown.ts

I might add a keyUp then? Usually I prefer that over keyDown to avoid multiple calls if the user keeps pressing longer than needed

**Comment by oxcened** [comment]
> > you should reuse this one https://github.com/fiscozen/design_system/blob/main/packages/composables/src/composables/useKeyDown.ts
> 
> I might add a keyUp then? Usually I prefer that over keyDown to avoid multiple calls if the user keeps pressing longer than needed

yeah sure

**Review by oxcened — APPROVED** [review]

**Pull request merged**
